DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRICES (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE DECIMAL(10, 2),
    CURR VARCHAR(3),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);
